#!/usr/bin/env bash

readonly origin_hook="$0"
readonly script="${HOME}/.git-hooks/script.sh"
readonly track_hook="${HOME}/.git-hooks/track"

if [ ! -f "${track_hook}" ]; then
  >&2 echo "WARNING: $0 cannot find tracking hook: ${track_hook}"
  exit 0
fi

standard_props='{}'
if [ ! -f "${script}" ]; then
  >&2 echo "WARNING: $0 cannot find tracking hook: ${track_hook}"
else
  standard_props="$("${script}" fmt_standard_props "$@")"
fi
readonly standard_props

readonly props="${standard_props}"

"${track_hook}" "${origin_hook}" "${props}"
