#!/usr/bin/env bash

>&2 echo ">>>> $0 -- $*"

readonly origin_hook="$0"
readonly track_hook="${HOME}/.git-hooks/track"

if [ ! -f "${track_hook}" ]; then
  >&2 echo "WARNING: $0 cannot find tracking hook: ${track_hook}"
  exit 0
fi

hook_args_json_arr="$(
  # Based on from https://stackoverflow.com/a/26809318
  printf '%s\n' "$@" | jq -R . | jq -sc '. | map(select(length > 0))'
)"; readonly hook_args_json_arr

standard_props="$(
  jq -c --argjson hook_args "$hook_args_json_arr" '. + { hook_args: $hook_args } ' <<< '{}'
)"; readonly standard_props

readonly props="${standard_props}"

"${track_hook}" "${origin_hook}" "${props}"
