#!/usr/bin/env bash

readonly hook_file="$1"
repo_dir="$(pwd)"; readonly repo_dir

( set -euo pipefail

  readonly fmt_vsn='0.1.1'
  logfile="$(gec_path_active)"; readonly logfile
  timestamp="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"; readonly timestamp
  ref="$(git rev-parse --abbrev-ref HEAD)"; readonly ref
  remote="$(git remote get-url origin)"; readonly remote

  echo -e "${fmt_vsn}\t${timestamp}\t${hook_file}\t${repo_dir}\t${ref}\t${remote}" \
    >> "${logfile}"

) || true

standard_hook="${repo_dir}/.git/hooks/$(basename "${hook_file}")"; readonly standard_hook

>&2 echo "Checking for ${standard_hook}…"
if [ -x "${standard_hook}" ]; then
  "${standard_hook}" "$@" <<< -
fi
