import = [
  "~/.config/alacritty/colors.toml"
]

[window]
  decorations = "None"
  startup_mode = "Maximized"

[font]
  normal = { family = "PT Mono" }
  size = 16

[cursor]
  blink_interval = 150

[bell]
  animation = "Linear"
  duration  = 20
  color     = "#550000"

[colors]
  draw_bold_text_with_bright_colors = true
