ENV['XDG_CONFIG_HOME'].
  then { (_1.nil? || _1.strip.empty?) ? "#{Dir.home}/.config" : _1 }.
  then { Pathname.new(_1) / 'Brewfile.d/*' }.
  then { Dir[_1] }.
  # See: https://github.com/Homebrew/homebrew-bundle/issues/521#issuecomment-509023309
  each { instance_eval File.read(_1) }

brew "automake"
brew "binutils"
brew "cmake"
brew "coreutils"
brew "findutils"
brew "flac"
brew "gawk"
brew "gettext", link: true
brew "gnu-getopt"
brew "gnu-indent"
brew "gnu-sed"
brew "gnu-tar"
brew "gnutls"
brew "go"
brew "hub"
brew "icu4c"
brew "jpeg"
brew "lame"
brew "libssh"
brew "libssh2"
brew "libtool"
brew "libvorbis"
brew "libxslt"
brew "libyaml"
brew "msgpack"
brew "ncdu"
brew "ncurses"
brew "pkg-config"
brew "readline"
brew "rename"
brew "utf8proc"
brew "watch"

cask "1password-cli"
# At the time of writing, macOS will try to prevent Alacritty from starting up.
# For the workaround, see the following GitHub link:
# https://github.com/alacritty/alacritty/issues/6500#issuecomment-1356318595
# ---
# tl;dr: Right click + Open in finder -- feels a little like security
# through obscurity if you ask me, but okay Tim Apple 🙄.
cask "alacritty"
# # This is commented out for the same reason as Signal is below.
# cask "alfred"
cask "docker"
cask "rectangle"
# # I had Signal already installed on a machine and homebrew doesn't seem to
# # gracefully handle that, so I'm leaving it out of the bundle for now as
# # preferable to uninstalling Signal on said machine and losing whatever subset
# # of message history may be unique to that particular install.
# cask "signal"
cask "vlc"

# These can probably be split out to a different file
cask "basictex"
cask "calibre"
