#!/bin/sh
# post-commit

FIND_KEYWORDS_PATH=~/.git_templates/hooks/find_keywords.sh

if [ -f "$FIND_KEYWORDS_PATH" ]; then
  . "$FIND_KEYWORDS_PATH"
else
  exit 1
fi

find_todo
find_console_writeline
