# https://github.com/brigade/overcommit

PreCommit:
  TrailingWhitespace:
    enabled: true
    problem_on_unmodified_line: ignore

  FearOfCommitment:
    enabled: true

  ShellCheck:
    enabled: true
    on_fail: warn

CommitMsg:
  HardTabs:
    enabled: true

  RussianNovel:
    enabled: true

PrePush:
  PrintDiffUrls:
    enabled: true
