#!/usr/bin/env bash

set -euo pipefail

dotfiles="$HOME/.dotfiles"

# This is a bit wacky, but couldn't quite get rcm to do what I wanted here
spectacle_shortcuts="Library/Application Support/Spectacle/Shortcuts.json"
spec_src="$dotfiles/tag-osx/$spectacle_shortcuts"
spec_dst="$HOME/$spectacle_shortcuts"

diff "$spec_src" "$spec_dst" >/dev/null 2>&1 \
  || cp -v "$spec_src" "$spec_dst"

iterm2_schemes_dir="$HOME/.iterm2-color-schemes"
if [ ! -d "$iterm2_schemes_dir" ]; then
  git clone --depth=1 'git@github.com:mbadolato/iTerm2-Color-Schemes.git' "$iterm2_schemes_dir"
fi

cat <<MESSAGE

NOTE: Please make sure iTerm2 is configured to load from "~/.iterm".

      This can be configured by navigating to "Preferences > General" and then
      looking for the phrase (near the bottom):

        "Load preferences from a custom folder or URL"

NOTE: This setup process currently does not account for any ssh configuration.

      Such things will bave to be managed manually for now.

MESSAGE
