#!/usr/bin/env bash

set -euo pipefail

dotfiles="$HOME/.dotfiles"
tag="macos"

function _setup_spectacle_shortcut {
  # This is a bit wacky, but couldn't quite get rcm to do what I wanted here
  local rel_path; rel_path="Library/Application Support/Spectacle/Shortcuts.json"
  local spec_src; spec_src="$dotfiles/tag-$tag/$rel_path"
  local spec_dst; spec_dst="$HOME/$rel_path"

  diff "$spec_src" "$spec_dst" >/dev/null 2>&1 \
    || cp -v "$spec_src" "$spec_dst"
}

function _setup_iterm_color_schemes {
  local schemes_dir; schemes_dir="$HOME/.iterm2-color-schemes"
  if [ ! -d "$schemes_dir" ]; then
    git clone --depth=1 'git@github.com:mbadolato/iTerm2-Color-Schemes.git' "$schemes_dir"
  fi
}

function _setup_ssh_keys {
  if [ ! -f "$HOME/.ssh/id_rsa" ] && [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
    if [ "$OP_SESSION_my" = "" ]; then
      eval $(op signin my)
    fi
    op get document id_rsa     --vault=Personal > "$HOME/.ssh/id_rsa"
    op get document id_rsa.pub --vault=Personal > "$HOME/.ssh/id_rsa.pub"
  fi
}

function _display_messages {
  if [ -z ${TERM+x} ] || [ "$TERM" = 'dumb' ]; then
    export TERM='xterm-256color'
  fi

  mdp <<MESSAGE

# Notes

## iTerm2 Configuration

Please make sure iTerm2 is configured to load from \`~/.iterm\`.

This can be configured by navigating to \`Preferences > General\` and then
looking for the phrase (near the bottom):

\`Load preferences from a custom folder or URL\`

Also, when importing color schemes from \`~/.iterm2-color-schemes\`, in case
finder is not configured to show hidden files/folders, you can quickly toggle
this with \`CMD + SHIFT + .\`.

Don't forget to not only import it, but then also configure it to be used as
well.

## SSH Configuration

This setup process currently attempts to auto-setup ssh keys, but does not
attempt to do anything for \`~/.ssh/config\`.

## Shell Restart

If this is the very first time running this on a given machine, you may want to
restart the shell or just hop into a new tab from this point.

I'd like to automate that, but in what I've tried so far, nothing has been
able to do the final transition from macOS' very old bash to zsh automatically,
so it's still a bit manual for now.

MESSAGE
}

_setup_spectacle_shortcut
_setup_iterm_color_schemes
_setup_ssh_keys
_display_messages
