#!/usr/bin/env bash

set -euo pipefail

_clone_iterm_color_schemes() {
  local schemes_repo='git@github.com:mbadolato/iTerm2-Color-Schemes.git'
  local schemes_dir="$HOME/.iterm2-color-schemes"

  if [ ! -d "$schemes_dir" ]; then
    git clone --depth=1 "$schemes_repo" "$schemes_dir"
  fi
}

_display_messages() {
  if [ -z ${TERM+x} ] || [ "$TERM" = 'dumb' ]; then
    export TERM='xterm-256color'
  fi

  mdp --nofade <<MSG

# Dotfiles setup complete (mostly...)!

Following slides contain futher information.

---

# iTerm2 Color Scheme import

This happens in a dropdown at the bottom right corner of:

\` iTerm2 > Preferences > Profiles > [Profile Name] > Colors \`

Typically, \`[Profile Name]\` will be \`Default\`, but not necessarily.

There should be a bunch in \`~/.iterm2-color-schemes\`; it may be helpful to
find this directory in the Finder dialog by showing hidden files with the
keyboard shortcut \`CMD + SHIFT + .\`.


---

# Shell Restart

If this is the very first time running this on a machine, you may want to
restart the shell or just hop into a new tab from this point.

I'd like to automate that, but nothing I've tried so far has been able to do
the final transition from macOS' very old bash to zsh automatically, so it's
still a bit manual for now.

---

# That's It!

You can exit by pressing 'q'.

MSG
}

_default() {
  _clone_iterm_color_schemes
  _display_messages
}

# ---

"${@:-_default}"
