#!/bin/sh

# Install plug.vim and plugins
if [ ! -e "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME/.vim/vimrc.plugins" +PlugInstall +qa

# Set up npm completion
npm completion > "$HOME/.completions/npm.completion.sh"

# Install global dependencies
cd "$HOME/.global-dependencies"

bundle install
npm install -g $(cat npm-packages | xargs)
