#!/usr/bin/env bash

function _symlink_projects_dotfiles_dir {
  local name="dotfiles"
  local src_dir_path="$HOME/.$name"
  local dir_path="$HOME/projects/misc/$name"

  test -d "$dir_path" || ln -s "$src_dir_path" "$dir_path"
}

_symlink_projects_dotfiles_dir

# Install plug.vim and plugins
if [ ! -e "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# NOTE: If we don't pipe this dummy file in, along with the `-` at the end, vim
#       displays a warning about input not being from a terminal, and then
#       breaks the terminal once it exits.
echo 'foo' | vim -u "$HOME/.vim/vimrc.plugins" +PlugInstall '+qa!' -

test -e "$HOME/.env-specific/post-up" && "$HOME/.env-specific/post-up"
