#!/usr/bin/env sh

# Install plug.vim and plugins
if [ ! -e "$HOME/.vim/autoload/plug.vim" ]; then
  curl -fLo "$HOME/.vim/autoload/plug.vim" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME/.vim/vimrc.plugins" +PlugInstall +qa

reset -Q

test -e "$HOME/.env-specific/post-up" && "$HOME/.env-specific/post-up"
