name: CI
on: [push]
jobs:
  dhall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awseward/gh-actions-dhall@0.2.9
        with:
          dhallVersion: 1.37.1

  shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: awseward/gh-actions-shell@0.1.5

  local:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run checks committed directly to repository
        run:  set -euo pipefail; find .checks -type f | while read -r check_file; do "${check_file}"; done
